header:
  version: 14

distro: poky
target: core-image-minimal

repos:
  poky:
    url: https://git.yoctoproject.org/poky
    branch: scarthgap
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
